fix(grafana): update version label format to adhere to Kubernetes conventions
Since it causes flux-local mistbahaving.

fix(istio): correct HelmRepository URL to use the appropriate Docker proxy

Since nju mirror doesn't support listing tags which causes flux-local fails:
flux-local error:  Command 'helm template istio-cni oci://gcr.nju.edu.cn/istio-release/charts/cni --namespace istio-system --repository-cache /tmp/tmpo02hbnz8 --repository-config /tmp/tmpbdctz5en/repository-config.yaml --registry-config /tmp/tmpkdx_34a9.json --skip-crds --skip-tests --version '1.29.*' --values /tmp/tmpbdctz5en/istio-system-istio-cni-values.yaml' failed with return code 1
Error: GET "https://gcr.nju.edu.cn/v2/istio-release/charts/cni/tags/list": response status code 500: unknown: unknown error: operation unsupported